{
 "title": "Directory Services Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ldap_handler", "query": "label_values(ldap_handler)" },
   { "name": "basedn", "query": "label_values(base_dn)" },
   {
    "name": "public_basedn",
    "query": "label_values(ds_backend_entry_count{type=\"db\"}, base_dn)"
   },
   {
    "name": "ds_job",
    "query": "label_values(ds_start_time_seconds, job)"
   },
   {
    "name": "ds_instance",
    "query": "label_values(ds_start_time_seconds, instance)"
   },
   {
    "name": "disk",
    "query": "label_values(ds_disk_free_space_bytes, disk)"
   },
   {
    "name": "domain",
    "query": "label_values(ds_replication_replica_remote_replicas_replayed_updates_count, domain_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overall Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Load",
   "type": "singlestat",
   "description": "This is the global average number of requests performed by the directory service.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(ds_connection_handlers_ldap_requests_count[30s]))",
     "target": "sumSeries(*.ds.connection-handlers.ldap.requests.m1_rate)"
    }
   ]
  },
  {
   "title": "Requests in Queue",
   "type": "singlestat",
   "description": "Number of requests in queue waiting to be processed",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ds_work_queue_requests_in_queue)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "description": "The recent average of errors occurring in the service. These errors could be tied to client applications, invalid data, authentication failures...",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(ds_connection_handlers_ldap_requests_failure_count[30s]))",
     "target": "sumSeries(*.ds.connection-handlers.ldap.requests.failures.m1_rate)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "The total number of client connections opened against the whole directory service.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ds_current_connections)" }
   ]
  },
  {
   "title": "Max Receive Latency",
   "type": "singlestat",
   "description": "This value represents the highest latency in receiving messages across all replicas, at each instant.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ds_replication_replica_remote_replicas_receive_delay_seconds)"
    }
   ]
  },
  {
   "title": "ForgeRock DS instances",
   "type": "graph",
   "description": "Numbers of DS, RS and proxies. Some instances may be combined DS/RS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up and ds_start_time_seconds)",
     "legendFormat": "Total number of ForgeRock DS instances"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{type=\"db\"}))",
     "legendFormat": "Number of DSs"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{base_dn=\"cn=changelog\"}))",
     "legendFormat": "Number of RSs"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{type=\"proxy\"}))",
     "legendFormat": "Number of Proxies"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(ds_connection_handlers_ldap_requests_failure_count[30s])",
     "legendFormat": "{{job}} {{instance}} - {{ldap_handler}} {{type}}"
    }
   ]
  },
  { "title": "Access Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Load Averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, instance, ldap_handler) (rate(ds_connection_handlers_ldap_requests_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m]))",
     "legendFormat": "{{job}} {{instance}} {{ldap_handler}} m1_rate",
     "target": "*.ds.connection-handlers.ldap.requests.m1_rate"
    },
    {
     "expr": "sum by (job, instance, ldap_handler) (rate(ds_connection_handlers_ldap_requests_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[5m]))",
     "legendFormat": "{{job}} {{instance}} {{ldap_handler}} m5_rate",
     "target": "*.ds.connection-handlers.ldap.requests.m5_rate"
    }
   ]
  },
  {
   "title": "Current response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, instance, ldap_handler, type) (irate(ds_connection_handlers_ldap_requests_seconds_total{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m])) / sum by (job, instance, ldap_handler, type) (irate(ds_connection_handlers_ldap_requests_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m]))",
     "legendFormat": "{{job}} {{instance}} - {{ldap_handler}} - {{type}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Receive Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ds_replication_replica_remote_replicas_receive_delay_seconds",
     "legendFormat": "DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Replay Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ds_replication_replica_remote_replicas_replay_delay_seconds",
     "legendFormat": "DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Replayed updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(ds_replication_replica_remote_replicas_replayed_updates_count{job=~\"$ds_job\",instance=~\"$ds_instance\",domain_name=~\"$domain\"}[30s])",
     "legendFormat": "{{job}} {{instance}} {{domain_name}} last 30s"
    },
    {
     "expr": "rate(ds_replication_replica_remote_replicas_replayed_updates_count{job=~\"$ds_job\",instance=~\"$ds_instance\",domain_name=~\"$domain\"}[5m])",
     "legendFormat": "{{job}} {{instance}} {{domain_name}} last 5m"
    }
   ]
  },
  { "title": "Backend: $public_basedn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "public_basedn" },
  {
   "title": "$ds_instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
   "repeat": "ds_instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ds_backend_entry_count{base_dn=~\"$public_basedn\", instance=~\"$ds_instance\"}"
    }
   ]
  },
  { "title": "Disk free: ${disk}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "disk" },
  {
   "title": "${ds_instance}",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 39 },
   "repeat": "ds_instance",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ds_disk_free_space_bytes{instance=~\"$ds_instance\", disk=~\"$disk\"}"
    }
   ]
  },
  { "title": "Health Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ds_jvm_memory_used_bytes{instance=~\"$ds_instance\"}",
     "legendFormat": "{{job}} {{instance}} JVM Total Memory Usage",
     "target": "*.ds.jvm-memory-usage.memory-usage.total.used"
    }
   ]
  },
  {
   "title": "Garbage Collections Time",
   "type": "graph",
   "description": "Time spent for garbage collections by minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ds_jvm_garbage_collector_g1_young_generation_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} G1 young gen collections time m1_rate"
    },
    {
     "expr": "rate(ds_jvm_garbage_collector_g1_old_generation_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} G1 old gen collections time m1_rate"
    }
   ]
  },
  {
   "title": "Garbage Collections: old gen memory after GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ds_jvm_memory_pools_g1_old_gen_used_after_gc_bytes",
     "legendFormat": "{{job}} {{instance}} G1 old gen used after GC"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Certificate expiry in",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ds_certificates_certificate_expires_at_seconds - time()",
     "legendFormat": "{{job}} {{instance}} \"{{key_manager}}\", {{alias}}"
    }
   ]
  }
 ]
}